apiVersion: v1
kind: Service
metadata:
  name: gitlab-backend-service
spec:
  type: LoadBalancer
  selector:
    app: gitlab-backend
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
